### ISSUE TITLE
Observations on Issues Raised during registration

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/test-registry#5]
@SvanteAlnas I understand that this is still under test but here you can find some feedback:
* [ ] the registrations have been done on behalf of OMA Admin account. Remember that we should aim for the user to provide his/her credentials to register these objects. In the absence of this credentials then we use the OMA Admin account

 * [ ] The information to be listed in the Issue should be:
   * [ ] Registration Type:
   * [ ] Submitter Name:
   * [ ] Object Type:
   * [ ] Company/Organization Name:
   * [ ] Object Name:
   * [ ] Short Description:
   * [x] License Type: **(if not too complicated to add**)        
      * It is not possible to add it.
   * [ ] View Object in LwM2M Editor Tool:
   * [ ] View xml file:
The email sent to helpdesk will also contain in addition of the above:
   * [ ] Submitter email:

**Comment by SvanteAlnas** [comment]
License type will not be added unless we store that information in the Object and today it is not stored there

The remaining above that does not already exist will be added

**Comment by SvanteAlnas** [comment]
Done except for the metadata that will be removed

**Comment by SvanteAlnas** [comment]
Done

**Comment by jpradocueva** [comment]
https://github.com/OpenMobileAlliance/OMA_LWM2M_Editor/issues/11
Closing this issue here.
